/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


int main(void)
{
	while(1) {
		int i = 0;
		int j = 0;
		int r = 0;
	//Green LED
	/*enabling pins*/
		uint32_t* rcc_c = (uint32_t*) (0x40021000  + 0x4c);
		*rcc_c |= (1U << 2); // write bit 2 as 1
		uint32_t x = *rcc_c; // read

	/*configure the pin1*/
		uint32_t* gpio_c_base = (uint32_t*) 0x48000800;
		//bit 14 to 1 to make this an output
		*gpio_c_base |= (1U << 14); // write
		*gpio_c_base = *gpio_c_base & ~(1U << 15); // write
		uint32_t c = *gpio_c_base; // read

	/*set it high*/
		uint32_t* gpio_c = (uint32_t*)(0x48000800 + 0x14);
		*gpio_c |= (1U << 7); // write
		uint32_t O = *gpio_c;

		while ( i < 100000) {
			i++;
		}

		*gpio_c = *gpio_c & ~(1U << 7);
		uint32_t t = *gpio_c;



	//blue LED

	/*enabling pins*/
		uint32_t* rcc_b = (uint32_t*) (0x40021000 + 0x4c);
		*rcc_b |= (1U << 1); // write bit 1 as 1
		uint32_t y = *rcc_b; // read

	/*configure the pin1*/
		uint32_t* gpio_b_base = (uint32_t*) 0x48000400;
		//bit 14 to 1 to make this an output
		*gpio_b_base |= (1U << 14); // write
		*gpio_b_base = *gpio_b_base & ~(1U << 15); // write
		uint32_t b = *gpio_b_base; // read

	/*set it high*/
		uint32_t* gpio_b = (uint32_t*)(0x48000400 + 0x14);
		*gpio_b |= (1U << 7); // write
		uint32_t D = *gpio_b;


		while ( j < 100000) {
					j++;
				}


	/*turn off*/
		*gpio_b = *gpio_b & ~(1U << 7);
		uint32_t e = *gpio_b;


	//red LED
	/*enabling pins*/
		uint32_t* rcc_b2 = (uint32_t*) (0x40021000 + 0x4c);
		*rcc_b2 = (1U << 1); // write bit 1 as 1
		uint32_t z = *rcc_b2; // read


	/*configure the pin1*/
		uint32_t* gpio_b2_base = (uint32_t*) 0x48000400;
		//bit 14 to 1 to make this an output
		*gpio_b2_base |= (1U << 28); // write
		*gpio_b2_base = *gpio_b2_base & ~(1U << 29); // write
		uint32_t b2 = *gpio_b2_base; // read

	/*set it high*/
		uint32_t* gpio_b2 = (uint32_t*)(0x48000400 + 0x14);
		*gpio_b2 |= (1U << 14); // write
		uint32_t D2 = *gpio_b2;

		while ( r < 100000) {
				r++;
			}

	/*turn off*/
		*gpio_b2 = *gpio_b2 & ~(1U << 14);
		uint32_t f = *gpio_b2;
	}
}



