/**
******************************************************************************
* @file           : main.c
* @author         : Auto-generated by STM32CubeIDE
* @brief          : Main program body
******************************************************************************
* @attention
*
* Copyright (c) 2026 STMicroelectronics.
* All rights reserved.
*
* This software is licensed under terms that can be found in the LICENSE file
* in the root directory of this software component.
* If no LICENSE file comes with this software, it is provided AS-IS.
*
******************************************************************************
*/
#include <stdint.h>
/**
******************************************************************************
* @file           : main.c
* @author         : Auto-generated by STM32CubeIDE
* @brief          : Main program body
******************************************************************************
* @attention
*
* Copyright (c) 2026 STMicroelectronics.
* All rights reserved.
*
* This software is licensed under terms that can be found in the LICENSE file
* in the root directory of this software component.
* If no LICENSE file comes with this software, it is provided AS-IS.
*
******************************************************************************
*/
#include <stdint.h>
int main(void)
{
//blue LED
/*enabling pins*/
	uint32_t* rcc_b = (uint32_t*) (0x40021000 + 0x4c);
	*rcc_b |= (1U << 1); // write bit 1 as 1
	uint32_t y = *rcc_b; // read
/*configure the pin1*/
	uint32_t* gpio_b_base = (uint32_t*) 0x48000400;
	//bit 14 to 1 to make this an output
	*gpio_b_base |= (1U << 14); // write
	*gpio_b_base = *gpio_b_base & ~(1U << 15); // write
	uint32_t b = *gpio_b_base; // read
/*set it high*/
	uint32_t* gpio_b = (uint32_t*)(0x48000400 + 0x14);
	*gpio_b |= (1U << 7); // write
	uint32_t D = *gpio_b;
	
/*turn off*/
	*gpio_b = *gpio_b & ~(1U << 7);
	uint32_t e = *gpio_b;
	
	
	__asm__ volatile (
	"LDR R0, =0x40021000\n\t" // Load address to R0
	"ADD R0, #0x4c" //add the offset to the base address
	"LDR R1, [R0]\n\t" // Load value of R0 to R1
	"ORR R1, R1, #2    \n"
   "STR R1, R2     \n"
	
	"LDR R3, =0x48000400\n\t"
	"ORR R3, R3, #0x4000"
	"BIC {R3,} R3, 0x8000 "
	"STR R3, R4"
			
	"LDR R5, =0x48000400\n\t"
	"ADD R5, #0x14"
	"LDR R6, [R5]\n\t"
	"ORR R6, R6, #0x80"
	"STR R6, R7"
	
   "BIC {R6,} R6, 0x80"
   "STR R6,R8"
			
	);
	while (1);
	
}
